name: Release Extension (v2)
on:
  repository_dispatch:
    types: [liquibase-release]
  workflow_dispatch:
    inputs:
      liquibaseVersion:
        description: 'Liquibase Version'
        required: true
      extensionVersion:
        description: 'Extension Version (Defaults to Liquibase Version)'
        required: false

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Collect Data
        id: collect-data
        uses: actions/github-script@v4
        with:
          script: |
            console.log(context.payload);

            if (github.event.client_payload) {
                core.setOutput("liquibaseVersion", github.event.client_payload.liquibaseVersion);
                core.setOutput("extensionVersion", github.event.client_payload.liquibaseVersion);
            } else if (github.event.inputs) {
                core.setOutput("liquibaseVersion", github.event.inputs.liquibaseVersion);
                core.setOutput("extensionVersion", github.event.inputs.extensionVersion || github.event.inputs.liquibaseVersion);
            } else {
              core.setFailed('Unknown event type')
            }

      - run: |
          echo "Saw Liquibase version ${{ steps.collect-data.outputs.liquibaseVersion }}"
          echo "Saw Extension version ${{ steps.collect-data.outputs.liquibaseVersion }}"
